"""add_gmail_credentials_suggested_companies

Revision ID: 0f8d4fdcc269
Revises: dbcfaa50bafe
Create Date: 2026-03-14 12:14:27.841862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8d4fdcc269'
down_revision: Union[str, None] = 'dbcfaa50bafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('history_id', sa.String(length=64), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('initial_sync_done', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gmail_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gmail_credentials_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gmail_credentials_user_id'), ['user_id'], unique=True)

    op.create_table('suggested_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_thread_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('asking_price', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('broker_name', sa.String(length=255), nullable=True),
    sa.Column('broker_email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_extract', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('promoted_company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['promoted_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_thread_id'], ['email_threads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggested_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggested_companies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggested_companies_source_thread_id'), ['source_thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggested_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggested_companies_source_thread_id'))
        batch_op.drop_index(batch_op.f('ix_suggested_companies_id'))

    op.drop_table('suggested_companies')
    with op.batch_alter_table('gmail_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gmail_credentials_user_id'))
        batch_op.drop_index(batch_op.f('ix_gmail_credentials_id'))

    op.drop_table('gmail_credentials')
    # ### end Alembic commands ###
