"""full_schema_v2

Revision ID: 8d2a6ff48a10
Revises: 
Create Date: 2026-03-14 11:24:11.695884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2a6ff48a10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('relationship_strength', sa.String(length=20), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('deal_count', sa.Integer(), nullable=True),
    sa.Column('avg_deal_size', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brokers_created_at'), 'brokers', ['created_at'], unique=False)
    op.create_index(op.f('ix_brokers_email'), 'brokers', ['email'], unique=False)
    op.create_index(op.f('ix_brokers_id'), 'brokers', ['id'], unique=False)
    op.create_table('comp_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sub_industry', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enterprise_value', sa.Float(), nullable=True),
    sa.Column('revenue_ttm', sa.Float(), nullable=True),
    sa.Column('ebitda_ttm', sa.Float(), nullable=True),
    sa.Column('ev_revenue_multiple', sa.Float(), nullable=True),
    sa.Column('ev_ebitda_multiple', sa.Float(), nullable=True),
    sa.Column('buyer_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes_text', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_transactions_created_at'), 'comp_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_comp_transactions_id'), 'comp_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_comp_transactions_industry'), 'comp_transactions', ['industry'], unique=False)
    op.create_table('lenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lender_type', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('max_loan_amount', sa.Float(), nullable=True),
    sa.Column('min_loan_amount', sa.Float(), nullable=True),
    sa.Column('sba_volume_rank', sa.Integer(), nullable=True),
    sa.Column('notes_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lenders_created_at'), 'lenders', ['created_at'], unique=False)
    op.create_index(op.f('ix_lenders_id'), 'lenders', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('gmail_tokens', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sub_industry', sa.String(length=100), nullable=True),
    sa.Column('annual_revenue', sa.Float(), nullable=True),
    sa.Column('revenue_ttm', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('ebitda_ttm', sa.Float(), nullable=True),
    sa.Column('ebitda_margin', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('sde_ttm', sa.Float(), nullable=True),
    sa.Column('asking_price', sa.Float(), nullable=True),
    sa.Column('implied_multiple', sa.Float(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('state_of_incorporation', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.Enum('LLC', 'S_CORP', 'C_CORP', 'SOLE_PROP', 'PARTNER', 'OTHER', name='entitytype'), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('deal_stage', sa.Enum('PROSPECT', 'CONTACTED', 'NDA', 'LOI', 'DD', 'CLOSED', 'PASSED', name='dealstage'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('listing_url', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('is_proprietary', sa.Boolean(), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('owner_phone', sa.String(length=50), nullable=True),
    sa.Column('lead_partner', sa.String(length=50), nullable=True),
    sa.Column('deal_score', sa.Float(), nullable=True),
    sa.Column('enrichment_score', sa.Float(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_score_rationale', sa.Text(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ein', sa.String(length=20), nullable=True),
    sa.Column('edgar_cik', sa.String(length=20), nullable=True),
    sa.Column('opencorporates_id', sa.String(length=100), nullable=True),
    sa.Column('google_place_id', sa.String(length=100), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_broker_id'), 'companies', ['broker_id'], unique=False)
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_deal_stage'), 'companies', ['deal_stage'], unique=False)
    op.create_index('ix_companies_deal_stage_active', 'companies', ['deal_stage', 'is_active'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index('ix_companies_lead_partner', 'companies', ['lead_partner'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_index(op.f('ix_companies_source'), 'companies', ['source'], unique=False)
    op.create_index(op.f('ix_companies_state'), 'companies', ['state'], unique=False)
    op.create_table('industry_kb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('sub_industry', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_kb_created_at'), 'industry_kb', ['created_at'], unique=False)
    op.create_index(op.f('ix_industry_kb_id'), 'industry_kb', ['id'], unique=False)
    op.create_index(op.f('ix_industry_kb_industry'), 'industry_kb', ['industry'], unique=False)
    op.create_table('broker_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_site', sa.String(length=50), nullable=False),
    sa.Column('listing_id', sa.String(length=255), nullable=True),
    sa.Column('listing_url', sa.String(length=1000), nullable=True),
    sa.Column('business_name', sa.String(length=500), nullable=True),
    sa.Column('asking_price', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('cash_flow', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_listed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_scraped', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('matched_company_id', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('broker_name', sa.String(length=200), nullable=True),
    sa.Column('broker_email', sa.String(length=255), nullable=True),
    sa.Column('broker_phone', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_site', 'listing_id', name='uq_broker_listing_site_id')
    )
    op.create_index(op.f('ix_broker_listings_broker_id'), 'broker_listings', ['broker_id'], unique=False)
    op.create_index(op.f('ix_broker_listings_broker_site'), 'broker_listings', ['broker_site'], unique=False)
    op.create_index(op.f('ix_broker_listings_created_at'), 'broker_listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_broker_listings_id'), 'broker_listings', ['id'], unique=False)
    op.create_index(op.f('ix_broker_listings_industry'), 'broker_listings', ['industry'], unique=False)
    op.create_index('ix_broker_listings_is_new', 'broker_listings', ['is_new'], unique=False)
    op.create_index(op.f('ix_broker_listings_listing_id'), 'broker_listings', ['listing_id'], unique=False)
    op.create_index(op.f('ix_broker_listings_matched_company_id'), 'broker_listings', ['matched_company_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('notes_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_broker_id'), 'contacts', ['broker_id'], unique=False)
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('period_quarter', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('ebit', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('capex', sa.Float(), nullable=True),
    sa.Column('owner_comp', sa.Float(), nullable=True),
    sa.Column('sde', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_year', 'period_type', 'period_quarter', name='uq_financials_company_period')
    )
    op.create_index(op.f('ix_financials_company_id'), 'financials', ['company_id'], unique=False)
    op.create_index(op.f('ix_financials_created_at'), 'financials', ['created_at'], unique=False)
    op.create_index(op.f('ix_financials_id'), 'financials', ['id'], unique=False)
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('conducted_by', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Enum('COMPLETED', 'NO_ANSWER', 'LEFT_VM', 'RESCHEDULED', 'CANCELLED', name='calloutcome'), nullable=True),
    sa.Column('prep_notes', sa.Text(), nullable=True),
    sa.Column('call_notes', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.String(length=1000), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conducted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_company_id'), 'call_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_call_logs_created_at'), 'call_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_call_logs_id'), 'call_logs', ['id'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('lender_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('deal_name', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.Enum('PROSPECT', 'CONTACTED', 'NDA', 'LOI', 'DD', 'CLOSED', 'PASSED', name='dealstage'), nullable=False),
    sa.Column('asking_price', sa.Float(), nullable=True),
    sa.Column('offer_price', sa.Float(), nullable=True),
    sa.Column('revenue_multiple', sa.Float(), nullable=True),
    sa.Column('ebitda_multiple', sa.Float(), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('target_close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passed_reason', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.String(length=50), nullable=True),
    sa.Column('sba_eligible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['broker_listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_broker_id'), 'deals', ['broker_id'], unique=False)
    op.create_index(op.f('ix_deals_company_id'), 'deals', ['company_id'], unique=False)
    op.create_index(op.f('ix_deals_created_at'), 'deals', ['created_at'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_stage'), 'deals', ['stage'], unique=False)
    op.create_table('email_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('full_body', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_broker', sa.Boolean(), nullable=False),
    sa.Column('matched_company_id', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('is_unread', sa.Boolean(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('raw_messages', sa.JSON(), nullable=True),
    sa.Column('linked_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_threads_company_id'), 'email_threads', ['company_id'], unique=False)
    op.create_index(op.f('ix_email_threads_created_at'), 'email_threads', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_threads_gmail_thread_id'), 'email_threads', ['gmail_thread_id'], unique=True)
    op.create_index(op.f('ix_email_threads_id'), 'email_threads', ['id'], unique=False)
    op.create_index('ix_email_threads_is_broker', 'email_threads', ['is_broker'], unique=False)
    op.create_index('ix_email_threads_is_processed', 'email_threads', ['is_processed'], unique=False)
    op.create_index(op.f('ix_email_threads_matched_company_id'), 'email_threads', ['matched_company_id'], unique=False)
    op.create_index(op.f('ix_email_threads_received_at'), 'email_threads', ['received_at'], unique=False)
    op.create_index(op.f('ix_email_threads_sender_email'), 'email_threads', ['sender_email'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.Enum('NDA', 'CIM', 'LOI', 'FINANCIAL', 'DD', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_deal_id'), 'documents', ['deal_id'], unique=False)
    op.create_index('ix_documents_doc_type', 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tagged_stage', sa.Enum('PROSPECT', 'CONTACTED', 'NDA', 'LOI', 'DD', 'CLOSED', 'PASSED', name='dealstage'), nullable=True),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_company_id'), 'notes', ['company_id'], unique=False)
    op.create_index(op.f('ix_notes_created_at'), 'notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_notes_deal_id'), 'notes', ['deal_id'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_table('outreach_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('sent_by', sa.Integer(), nullable=True),
    sa.Column('contact_method', sa.Enum('EMAIL', 'PHONE', 'LINKEDIN', 'LETTER', 'IN_PERSON', 'OTHER', name='contactmethod'), nullable=False),
    sa.Column('direction', sa.Enum('OUTBOUND', 'INBOUND', name='outreachdirection'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('NO_RESPONSE', 'POSITIVE', 'NEGATIVE', 'MEETING_BOOKED', 'NDA_REQUESTED', 'PASSED', 'PENDING', name='outreachoutcome'), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_thread_id', sa.Integer(), nullable=True),
    sa.Column('sequence_step', sa.Integer(), nullable=True),
    sa.Column('template_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_thread_id'], ['email_threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outreach_follow_up', 'outreach_log', ['follow_up_date'], unique=False)
    op.create_index(op.f('ix_outreach_log_company_id'), 'outreach_log', ['company_id'], unique=False)
    op.create_index(op.f('ix_outreach_log_created_at'), 'outreach_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_log_id'), 'outreach_log', ['id'], unique=False)
    op.create_index('ix_outreach_outcome', 'outreach_log', ['outcome'], unique=False)
    op.create_table('cim_extracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('business_summary', sa.Text(), nullable=True),
    sa.Column('key_products', sa.JSON(), nullable=True),
    sa.Column('customer_concentration', sa.Float(), nullable=True),
    sa.Column('revenue_recurring_pct', sa.Float(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('key_risks', sa.JSON(), nullable=True),
    sa.Column('growth_opportunities', sa.JSON(), nullable=True),
    sa.Column('financials_summary', sa.JSON(), nullable=True),
    sa.Column('deal_score', sa.Float(), nullable=True),
    sa.Column('score_rationale', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cim_extracts_company_id'), 'cim_extracts', ['company_id'], unique=False)
    op.create_index(op.f('ix_cim_extracts_created_at'), 'cim_extracts', ['created_at'], unique=False)
    op.create_index(op.f('ix_cim_extracts_id'), 'cim_extracts', ['id'], unique=False)
    op.create_table('ndas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'SIGNED', 'EXPIRED', name='ndastatus'), nullable=True),
    sa.Column('sent_to_email', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signatory_name', sa.String(length=200), nullable=True),
    sa.Column('esign_provider', sa.String(length=50), nullable=True),
    sa.Column('esign_envelope_id', sa.String(length=255), nullable=True),
    sa.Column('ai_review_notes', sa.Text(), nullable=True),
    sa.Column('redlines', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ndas_company_id'), 'ndas', ['company_id'], unique=False)
    op.create_index(op.f('ix_ndas_created_at'), 'ndas', ['created_at'], unique=False)
    op.create_index(op.f('ix_ndas_id'), 'ndas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ndas_id'), table_name='ndas')
    op.drop_index(op.f('ix_ndas_created_at'), table_name='ndas')
    op.drop_index(op.f('ix_ndas_company_id'), table_name='ndas')
    op.drop_table('ndas')
    op.drop_index(op.f('ix_cim_extracts_id'), table_name='cim_extracts')
    op.drop_index(op.f('ix_cim_extracts_created_at'), table_name='cim_extracts')
    op.drop_index(op.f('ix_cim_extracts_company_id'), table_name='cim_extracts')
    op.drop_table('cim_extracts')
    op.drop_index('ix_outreach_outcome', table_name='outreach_log')
    op.drop_index(op.f('ix_outreach_log_id'), table_name='outreach_log')
    op.drop_index(op.f('ix_outreach_log_created_at'), table_name='outreach_log')
    op.drop_index(op.f('ix_outreach_log_company_id'), table_name='outreach_log')
    op.drop_index('ix_outreach_follow_up', table_name='outreach_log')
    op.drop_table('outreach_log')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_deal_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_created_at'), table_name='notes')
    op.drop_index(op.f('ix_notes_company_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index('ix_documents_doc_type', table_name='documents')
    op.drop_index(op.f('ix_documents_deal_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_email_threads_sender_email'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_received_at'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_matched_company_id'), table_name='email_threads')
    op.drop_index('ix_email_threads_is_processed', table_name='email_threads')
    op.drop_index('ix_email_threads_is_broker', table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_gmail_thread_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_created_at'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_company_id'), table_name='email_threads')
    op.drop_table('email_threads')
    op.drop_index(op.f('ix_deals_stage'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_created_at'), table_name='deals')
    op.drop_index(op.f('ix_deals_company_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_broker_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_call_logs_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_created_at'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_company_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_financials_id'), table_name='financials')
    op.drop_index(op.f('ix_financials_created_at'), table_name='financials')
    op.drop_index(op.f('ix_financials_company_id'), table_name='financials')
    op.drop_table('financials')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_broker_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_broker_listings_matched_company_id'), table_name='broker_listings')
    op.drop_index(op.f('ix_broker_listings_listing_id'), table_name='broker_listings')
    op.drop_index('ix_broker_listings_is_new', table_name='broker_listings')
    op.drop_index(op.f('ix_broker_listings_industry'), table_name='broker_listings')
    op.drop_index(op.f('ix_broker_listings_id'), table_name='broker_listings')
    op.drop_index(op.f('ix_broker_listings_created_at'), table_name='broker_listings')
    op.drop_index(op.f('ix_broker_listings_broker_site'), table_name='broker_listings')
    op.drop_index(op.f('ix_broker_listings_broker_id'), table_name='broker_listings')
    op.drop_table('broker_listings')
    op.drop_index(op.f('ix_industry_kb_industry'), table_name='industry_kb')
    op.drop_index(op.f('ix_industry_kb_id'), table_name='industry_kb')
    op.drop_index(op.f('ix_industry_kb_created_at'), table_name='industry_kb')
    op.drop_table('industry_kb')
    op.drop_index(op.f('ix_companies_state'), table_name='companies')
    op.drop_index(op.f('ix_companies_source'), table_name='companies')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index('ix_companies_lead_partner', table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index('ix_companies_deal_stage_active', table_name='companies')
    op.drop_index(op.f('ix_companies_deal_stage'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_broker_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lenders_id'), table_name='lenders')
    op.drop_index(op.f('ix_lenders_created_at'), table_name='lenders')
    op.drop_table('lenders')
    op.drop_index(op.f('ix_comp_transactions_industry'), table_name='comp_transactions')
    op.drop_index(op.f('ix_comp_transactions_id'), table_name='comp_transactions')
    op.drop_index(op.f('ix_comp_transactions_created_at'), table_name='comp_transactions')
    op.drop_table('comp_transactions')
    op.drop_index(op.f('ix_brokers_id'), table_name='brokers')
    op.drop_index(op.f('ix_brokers_email'), table_name='brokers')
    op.drop_index(op.f('ix_brokers_created_at'), table_name='brokers')
    op.drop_table('brokers')
    # ### end Alembic commands ###
