"""add_deal_scores

Revision ID: 8e76215dab3c
Revises: 8be0200d9500
Create Date: 2026-03-14 13:07:37.840358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e76215dab3c'
down_revision: Union[str, None] = '8be0200d9500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('cim_extract_id', sa.Integer(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('financial_quality', sa.JSON(), nullable=True),
    sa.Column('business_quality', sa.JSON(), nullable=True),
    sa.Column('operator_fit', sa.JSON(), nullable=True),
    sa.Column('deal_structure', sa.JSON(), nullable=True),
    sa.Column('growth_potential', sa.JSON(), nullable=True),
    sa.Column('deal_memo', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cim_extract_id'], ['cim_extracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_scores_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_scores_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_scores_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_scores_id'))
        batch_op.drop_index(batch_op.f('ix_deal_scores_created_at'))
        batch_op.drop_index(batch_op.f('ix_deal_scores_company_id'))

    op.drop_table('deal_scores')
    # ### end Alembic commands ###
