"""add_enrichment_log

Revision ID: c4fc20616842
Revises: 0f8d4fdcc269
Create Date: 2026-03-14 12:28:50.137171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4fc20616842'
down_revision: Union[str, None] = '0f8d4fdcc269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('fields_found', sa.JSON(), nullable=True),
    sa.Column('fields_missing', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichment_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrichment_log_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_log_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrichment_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrichment_log_id'))
        batch_op.drop_index(batch_op.f('ix_enrichment_log_company_id'))

    op.drop_table('enrichment_log')
    # ### end Alembic commands ###
