"""add_scraper_config_and_run_logs

Revision ID: dbcfaa50bafe
Revises: 8d2a6ff48a10
Create Date: 2026-03-14 11:57:03.074019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbcfaa50bafe'
down_revision: Union[str, None] = '8d2a6ff48a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_enabled', sa.JSON(), nullable=False),
    sa.Column('min_revenue', sa.Float(), nullable=True),
    sa.Column('max_revenue', sa.Float(), nullable=True),
    sa.Column('min_asking_price', sa.Float(), nullable=True),
    sa.Column('max_asking_price', sa.Float(), nullable=True),
    sa.Column('min_ebitda', sa.Float(), nullable=True),
    sa.Column('max_ebitda', sa.Float(), nullable=True),
    sa.Column('industries_include', sa.JSON(), nullable=True),
    sa.Column('industries_exclude', sa.JSON(), nullable=True),
    sa.Column('geo_states', sa.JSON(), nullable=True),
    sa.Column('keywords_include', sa.Text(), nullable=True),
    sa.Column('keywords_exclude', sa.Text(), nullable=True),
    sa.Column('run_schedule', sa.String(length=20), nullable=True),
    sa.Column('max_listings_per_site', sa.Integer(), nullable=True),
    sa.Column('request_delay_seconds', sa.Float(), nullable=True),
    sa.Column('max_pages_per_site', sa.Integer(), nullable=True),
    sa.Column('rotate_user_agents', sa.Boolean(), nullable=True),
    sa.Column('respect_robots_txt', sa.Boolean(), nullable=True),
    sa.Column('fuzzy_match_threshold', sa.Float(), nullable=True),
    sa.Column('auto_link_matches', sa.Boolean(), nullable=True),
    sa.Column('cross_site_dedup', sa.Boolean(), nullable=True),
    sa.Column('notify_new_listings', sa.Boolean(), nullable=True),
    sa.Column('notify_min_asking_price', sa.Float(), nullable=True),
    sa.Column('notify_min_revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_config_created_at'), 'scraper_config', ['created_at'], unique=False)
    op.create_index(op.f('ix_scraper_config_id'), 'scraper_config', ['id'], unique=False)
    op.create_table('scraper_run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('sites_run', sa.Integer(), nullable=True),
    sa.Column('pages_scraped', sa.Integer(), nullable=True),
    sa.Column('listings_found', sa.Integer(), nullable=True),
    sa.Column('listings_new', sa.Integer(), nullable=True),
    sa.Column('listings_dupes', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('per_site_stats', sa.JSON(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['scraper_config.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_run_logs_config_id'), 'scraper_run_logs', ['config_id'], unique=False)
    op.create_index(op.f('ix_scraper_run_logs_created_at'), 'scraper_run_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scraper_run_logs_id'), 'scraper_run_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraper_run_logs_id'), table_name='scraper_run_logs')
    op.drop_index(op.f('ix_scraper_run_logs_created_at'), table_name='scraper_run_logs')
    op.drop_index(op.f('ix_scraper_run_logs_config_id'), table_name='scraper_run_logs')
    op.drop_table('scraper_run_logs')
    op.drop_index(op.f('ix_scraper_config_id'), table_name='scraper_config')
    op.drop_index(op.f('ix_scraper_config_created_at'), table_name='scraper_config')
    op.drop_table('scraper_config')
    # ### end Alembic commands ###
